package io.github.geoverselabs.mybatis.geometry.interceptor;

import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.read.ListAppender;
import io.github.geoverselabs.mybatis.geometry.strategy.DatabaseType;
import io.github.geoverselabs.mybatis.geometry.strategy.GeometryHandlerStrategy;
import io.github.geoverselabs.mybatis.geometry.strategy.GeometryStrategyFactory;
import io.github.geoverselabs.mybatis.geometry.strategy.MySQLGeometryStrategy;
import io.github.geoverselabs.mybatis.geometry.strategy.PostGISGeometryStrategy;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.slf4j.LoggerFactory;

import java.util.List;
import java.util.Set;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.junit.jupiter.params.provider.Arguments.arguments;

class GeometrySqlRewriterTest {

    /** Columns of the {@code shop} entity: key, a plain column and one geometry column. */
    private static final GeometryColumns SHOP =
        new GeometryColumns("shop", List.of("location"), List.of("id", "name", "location"));

    @AfterEach
    void resetDefaultStrategy() {
        GeometryStrategyFactory.clearCache();
    }

    private static String mysql(String sql) {
        return new GeometrySqlRewriter(new MySQLGeometryStrategy()).rewrite(sql, SHOP, false);
    }

    static Stream<Arguments> mysqlCases() {
        return Stream.of(
            // ---- SQL generated by BaseMapper methods
            arguments("selectById",
                "SELECT id,name,location FROM shop WHERE id=? ",
                "SELECT id,name,HEX(location) AS location FROM shop WHERE id=? "),
            arguments("selectList with wrapper",
                "SELECT id,name,location FROM shop WHERE (name = ?)",
                "SELECT id,name,HEX(location) AS location FROM shop WHERE (name = ?)"),
            arguments("selectList with sqlFirst and sqlComment",
                "/* first */ SELECT id,name,location FROM shop WHERE (name = ?) /* comment */",
                "/* first */ SELECT id,name,HEX(location) AS location FROM shop WHERE (name = ?) /* comment */"),
            arguments("selectPage MySQL limit",
                "SELECT id,name,location FROM shop WHERE deleted=0 LIMIT ?",
                "SELECT id,name,HEX(location) AS location FROM shop WHERE deleted=0 LIMIT ?"),
            arguments("selectPage MySQL offset limit",
                "SELECT id,name,location FROM shop WHERE deleted=0 LIMIT ?,?",
                "SELECT id,name,HEX(location) AS location FROM shop WHERE deleted=0 LIMIT ?,?"),
            arguments("selectPage limit offset",
                "SELECT id,name,location FROM shop ORDER BY id ASC LIMIT ? OFFSET ?",
                "SELECT id,name,HEX(location) AS location FROM shop ORDER BY id ASC LIMIT ? OFFSET ?"),
            arguments("selectPage count",
                "SELECT COUNT(*) AS total FROM shop WHERE deleted = 0",
                "SELECT COUNT(*) AS total FROM shop WHERE deleted = 0"),
            arguments("selectCount",
                "SELECT COUNT( * ) AS total FROM shop",
                "SELECT COUNT( * ) AS total FROM shop"),
            arguments("select subset with geometry",
                "SELECT id,location FROM shop WHERE (id IN (?,?))",
                "SELECT id,HEX(location) AS location FROM shop WHERE (id IN (?,?))"),
            arguments("select subset without geometry",
                "SELECT id,name FROM shop",
                "SELECT id,name FROM shop"),
            arguments("logic delete",
                "SELECT id,name,location FROM shop WHERE id=? AND deleted=0",
                "SELECT id,name,HEX(location) AS location FROM shop WHERE id=? AND deleted=0"),
            arguments("column re-aliased by MyBatis-Plus",
                "SELECT id,name,location AS loc FROM shop",
                "SELECT id,name,HEX(location) AS loc FROM shop"),
            arguments("JSqlParser re-serialised (tenant/data permission interceptors)",
                "SELECT id, from_city, location FROM shop WHERE id = ? AND tenant_id = 1",
                "SELECT id, from_city, HEX(location) AS location FROM shop WHERE id = ? AND tenant_id = 1"),
            // ---- SELECT *
            arguments("select star",
                "SELECT * FROM shop WHERE name = ?",
                "SELECT id, name, HEX(location) AS location FROM shop WHERE name = ?"),
            arguments("select star with alias",
                "SELECT * FROM shop s WHERE s.name = ?",
                "SELECT s.id, s.name, HEX(s.location) AS location FROM shop s WHERE s.name = ?"),
            arguments("qualified star",
                "SELECT s.* FROM shop s WHERE s.id = ?",
                "SELECT s.id, s.name, HEX(s.location) AS location FROM shop s WHERE s.id = ?"),
            arguments("qualified star by table name",
                "SELECT shop.* FROM shop",
                "SELECT shop.id, shop.name, HEX(shop.location) AS location FROM shop"),
            arguments("star of another table",
                "SELECT x.* FROM shop s",
                "SELECT x.* FROM shop s"),
            arguments("star next to other items",
                "SELECT *, location AS raw FROM shop",
                "SELECT id, name, HEX(location) AS location, HEX(location) AS raw FROM shop"),
            arguments("multi-line star",
                "SELECT *\nFROM shop\nWHERE name = ?",
                "SELECT id, name, HEX(location) AS location\nFROM shop\nWHERE name = ?"),
            arguments("count star is an expression",
                "SELECT COUNT(*) FROM shop",
                "SELECT COUNT(*) FROM shop"),
            // ---- explicit column forms
            arguments("distinct",
                "SELECT DISTINCT location FROM shop WHERE deleted=0 LIMIT ?",
                "SELECT DISTINCT HEX(location) AS location FROM shop WHERE deleted=0 LIMIT ?"),
            arguments("optimizer hint",
                "SELECT /*+ MAX_EXECUTION_TIME(1000) */ location FROM shop",
                "SELECT /*+ MAX_EXECUTION_TIME(1000) */ HEX(location) AS location FROM shop"),
            arguments("hint and distinct before a comment",
                "SELECT /*+ NO_INDEX(shop) */ DISTINCT /* geo */ location, id FROM shop",
                "SELECT /*+ NO_INDEX(shop) */ DISTINCT /* geo */ HEX(location) AS location, id FROM shop"),
            arguments("backtick quoted column",
                "SELECT id, `location` FROM `shop`",
                "SELECT id, HEX(`location`) AS `location` FROM `shop`"),
            arguments("quoted qualifier and column",
                "SELECT `s`.`location` FROM shop `s`",
                "SELECT HEX(`s`.`location`) AS `location` FROM shop `s`"),
            arguments("alias without AS",
                "SELECT w.location loc, w.name FROM shop w",
                "SELECT HEX(w.location) AS loc, w.name FROM shop w"),
            arguments("alias with AS, quoted",
                "SELECT location AS `geo loc` FROM shop",
                "SELECT HEX(location) AS `geo loc` FROM shop"),
            arguments("string alias",
                "SELECT location AS 'loc' FROM shop",
                "SELECT HEX(location) AS 'loc' FROM shop"),
            arguments("case-insensitive names",
                "SELECT ID, LOCATION FROM SHOP",
                "SELECT ID, HEX(LOCATION) AS LOCATION FROM SHOP"),
            arguments("qualified by table name",
                "SELECT shop.location FROM shop",
                "SELECT HEX(shop.location) AS location FROM shop"),
            arguments("schema qualified",
                "SELECT db.shop.location FROM db.shop",
                "SELECT HEX(db.shop.location) AS location FROM db.shop"),
            arguments("qualified by the table name while aliased",
                "SELECT shop.location FROM shop s",
                "SELECT shop.location FROM shop s"),
            arguments("qualified by another table",
                "SELECT other.location FROM shop",
                "SELECT other.location FROM shop"),
            arguments("expressions are never touched",
                "SELECT ST_AsText(location) AS wkt, location IS NULL AS missing, location + 0, location FROM shop",
                "SELECT ST_AsText(location) AS wkt, location IS NULL AS missing, location + 0, HEX(location) AS location FROM shop"),
            arguments("collate expression",
                "SELECT location COLLATE utf8mb4_bin FROM shop",
                "SELECT location COLLATE utf8mb4_bin FROM shop"),
            arguments("string literals with commas, parentheses and from",
                "SELECT 'a,b' AS lbl, ':)' AS face, location FROM shop WHERE name = 'x from y'",
                "SELECT 'a,b' AS lbl, ':)' AS face, HEX(location) AS location FROM shop WHERE name = 'x from y'"),
            arguments("column named like from",
                "SELECT id, from_date, location FROM shop",
                "SELECT id, from_date, HEX(location) AS location FROM shop"),
            arguments("FROM inside a function",
                "SELECT EXTRACT(YEAR FROM created_at) AS y, TRIM(LEADING ' ' FROM name), location FROM shop",
                "SELECT EXTRACT(YEAR FROM created_at) AS y, TRIM(LEADING ' ' FROM name), HEX(location) AS location FROM shop"),
            arguments("multi-line explicit columns",
                "SELECT id,\n       location\n  FROM shop\n WHERE id = ?",
                "SELECT id,\n       HEX(location) AS location\n  FROM shop\n WHERE id = ?"),
            arguments("comments containing SQL",
                "SELECT id, -- location, FROM x\n location FROM shop # trailing location",
                "SELECT id, -- location, FROM x\n HEX(location) AS location FROM shop # trailing location"),
            arguments("for update",
                "SELECT id, location FROM shop WHERE id = ? FOR UPDATE",
                "SELECT id, HEX(location) AS location FROM shop WHERE id = ? FOR UPDATE"),
            arguments("trailing semicolon",
                "SELECT location FROM shop;",
                "SELECT HEX(location) AS location FROM shop;"),
            // ---- subqueries are never rewritten
            arguments("exists subquery with star",
                "SELECT id,name FROM shop WHERE (EXISTS (SELECT * FROM region r WHERE r.shop_id = shop.id))",
                "SELECT id,name FROM shop WHERE (EXISTS (SELECT * FROM region r WHERE r.shop_id = shop.id))"),
            arguments("exists subquery next to a geometry column",
                "SELECT id,location FROM shop WHERE EXISTS (SELECT * FROM region r WHERE r.location IS NOT NULL)",
                "SELECT id,HEX(location) AS location FROM shop WHERE EXISTS (SELECT * FROM region r WHERE r.location IS NOT NULL)"),
            arguments("inSql subquery",
                "SELECT id FROM shop WHERE (id IN (SELECT location FROM shop))",
                "SELECT id FROM shop WHERE (id IN (SELECT location FROM shop))"),
            arguments("scalar subquery in the select list",
                "SELECT (SELECT location FROM shop LIMIT 1) AS l, location FROM shop",
                "SELECT (SELECT location FROM shop LIMIT 1) AS l, HEX(location) AS location FROM shop"),
            arguments("derived table",
                "SELECT location FROM (SELECT location FROM shop) t",
                "SELECT location FROM (SELECT location FROM shop) t"),
            arguments("with clause",
                "WITH s AS (SELECT * FROM shop) SELECT location FROM s",
                "WITH s AS (SELECT * FROM shop) SELECT location FROM s"),
            arguments("union",
                "SELECT location FROM shop UNION ALL SELECT location FROM shop",
                "SELECT location FROM shop UNION ALL SELECT location FROM shop"),
            // ---- joins
            arguments("join: same-named column of another table",
                "SELECT s.id, c.location FROM shop s JOIN city c ON c.id = s.city_id",
                "SELECT s.id, c.location FROM shop s JOIN city c ON c.id = s.city_id"),
            arguments("join: main table column wrapped only",
                "SELECT s.location, c.location AS city_loc FROM shop s LEFT JOIN city c ON c.id = s.city_id",
                "SELECT HEX(s.location) AS location, c.location AS city_loc FROM shop s LEFT JOIN city c ON c.id = s.city_id"),
            arguments("join: unqualified star is not expanded",
                "SELECT * FROM shop s JOIN city c ON c.id = s.city_id",
                "SELECT * FROM shop s JOIN city c ON c.id = s.city_id"),
            arguments("comma join: unqualified star is not expanded",
                "SELECT *, location FROM shop, city",
                "SELECT *, HEX(location) AS location FROM shop, city"),
            arguments("join: star of the main table is expanded",
                "SELECT s.*, c.name FROM shop s JOIN city c ON c.id = s.city_id",
                "SELECT s.id, s.name, HEX(s.location) AS location, c.name FROM shop s JOIN city c ON c.id = s.city_id"),
            // ---- not SELECT / malformed
            arguments("not a select",
                "UPDATE shop SET location = ? WHERE id = ?",
                "UPDATE shop SET location = ? WHERE id = ?"),
            arguments("unbalanced",
                "SELECT location FROM shop WHERE (id = ?",
                "SELECT location FROM shop WHERE (id = ?"),
            arguments("unterminated string",
                "SELECT location FROM shop WHERE name = 'x",
                "SELECT location FROM shop WHERE name = 'x"),
            arguments("no geometry name and no star",
                "SELECT id FROM shop",
                "SELECT id FROM shop")
        );
    }

    @ParameterizedTest(name = "{0}")
    @MethodSource("mysqlCases")
    void rewritesMySqlStatements(String name, String sql, String expected) {
        assertThat(mysql(sql)).isEqualTo(expected);
    }

    @ParameterizedTest(name = "{0}")
    @MethodSource("mysqlCases")
    void rewritingIsIdempotent(String name, String sql, String expected) {
        assertThat(mysql(expected)).isEqualTo(expected);
    }

    @Test
    void unchangedSqlIsReturnedAsTheSameInstance() {
        String sql = "SELECT id FROM shop WHERE location IS NULL";
        assertThat(mysql(sql)).isSameAs(sql);
    }

    @Test
    void dollarSignsInColumnNames() {
        GeometryColumns columns = new GeometryColumns("t", List.of("geo$loc"), List.of("id", "geo$loc"));
        GeometrySqlRewriter rewriter = new GeometrySqlRewriter(new MySQLGeometryStrategy());
        assertThat(rewriter.rewrite("SELECT * FROM t", columns, true))
            .isEqualTo("SELECT id, HEX(geo$loc) AS geo$loc FROM t");
        assertThat(rewriter.rewrite("SELECT id, geo$loc FROM t WHERE x = '$1'", columns, true))
            .isEqualTo("SELECT id, HEX(geo$loc) AS geo$loc FROM t WHERE x = '$1'");
    }

    @Test
    void columnNamesAreComparedWithoutQuotes() {
        GeometryColumns quoted = new GeometryColumns("`spot`", List.of("`point`"), List.of("id", "`point`"));
        GeometrySqlRewriter rewriter = new GeometrySqlRewriter(new MySQLGeometryStrategy());
        assertThat(rewriter.rewrite("SELECT id,`point` FROM `spot` WHERE id=?", quoted, true))
            .isEqualTo("SELECT id,HEX(`point`) AS `point` FROM `spot` WHERE id=?");
        assertThat(rewriter.rewrite("SELECT id, point FROM spot", quoted, true))
            .isEqualTo("SELECT id, HEX(point) AS point FROM spot");
        assertThat(rewriter.rewrite("SELECT * FROM spot", quoted, true))
            .isEqualTo("SELECT id, HEX(`point`) AS `point` FROM spot");
    }

    @Test
    void mybatisPlusPropertyAliasIsKept() {
        GeometryColumns columns = new GeometryColumns("shop", List.of("geo_loc"), List.of("id", "geo_loc"));
        assertThat(new GeometrySqlRewriter(new MySQLGeometryStrategy())
            .rewrite("SELECT id,geo_loc AS location FROM shop WHERE id=?", columns, true))
            .isEqualTo("SELECT id,HEX(geo_loc) AS location FROM shop WHERE id=?");
    }

    @Test
    void pathologicalInputIsLinear() {
        // the former regex needed 762 ms for 1000 spaces and did not finish for 4000
        GeometrySqlRewriter rewriter = new GeometrySqlRewriter(new MySQLGeometryStrategy());
        long start = System.nanoTime();
        String spaces = "SELECT" + " ".repeat(100_000) + "location";
        assertThat(rewriter.rewrite(spaces, SHOP, false)).isSameAs(spaces);
        StringBuilder items = new StringBuilder("SELECT ST_Collect(ARRAY[");
        for (int i = 0; i < 5000; i++) {
            items.append(i == 0 ? "" : ",").append("ST_Point(?, ?)");
        }
        String noFrom = items.append("]) AS location").toString();
        assertThat(rewriter.rewrite(noFrom, SHOP, false)).isSameAs(noFrom);
        assertThat(System.nanoTime() - start).isLessThan(2_000_000_000L);
    }

    // ------------------------------------------------------------------ table matching

    @Test
    void requireTableMatchSkipsOtherTables() {
        GeometrySqlRewriter rewriter = new GeometrySqlRewriter(new MySQLGeometryStrategy());
        assertThat(rewriter.rewrite("SELECT id, location FROM city", SHOP, true))
            .isEqualTo("SELECT id, location FROM city");
        assertThat(rewriter.rewrite("SELECT id, location FROM shop", SHOP, true))
            .isEqualTo("SELECT id, HEX(location) AS location FROM shop");
        assertThat(rewriter.rewrite("SELECT id, location FROM `SHOP` s", SHOP, true))
            .isEqualTo("SELECT id, HEX(location) AS location FROM `SHOP` s");
        assertThat(rewriter.rewrite("SELECT id, location FROM db.shop", SHOP, true))
            .isEqualTo("SELECT id, HEX(location) AS location FROM db.shop");
    }

    @Test
    void entityResultsAreWrappedWhateverTheTableButStarNeedsTheEntityTable() {
        GeometrySqlRewriter rewriter = new GeometrySqlRewriter(new MySQLGeometryStrategy());
        // e.g. a dynamic table name (shop_2024) for a statement that maps rows onto the entity
        assertThat(rewriter.rewrite("SELECT id, location FROM shop_2024", SHOP, false))
            .isEqualTo("SELECT id, HEX(location) AS location FROM shop_2024");
        assertThat(rewriter.rewrite("SELECT * FROM shop_2024", SHOP, false))
            .isEqualTo("SELECT * FROM shop_2024");
        assertThat(rewriter.rewrite("SELECT s.* FROM shop_2024 s", SHOP, false))
            .isEqualTo("SELECT s.* FROM shop_2024 s");
    }

    @Test
    void unknownColumnsOrTableDisableOnlyWhatNeedsThem() {
        GeometrySqlRewriter rewriter = new GeometrySqlRewriter(new MySQLGeometryStrategy());
        GeometryColumns noColumns = new GeometryColumns("shop", List.of("location"), null);
        assertThat(rewriter.rewrite("SELECT *, location FROM shop", noColumns, true))
            .isEqualTo("SELECT *, HEX(location) AS location FROM shop");
        GeometryColumns noTable = new GeometryColumns(null, List.of("location"), List.of("id", "location"));
        assertThat(rewriter.rewrite("SELECT * FROM anything", noTable, true))
            .isEqualTo("SELECT id, HEX(location) AS location FROM anything");
    }

    @Test
    void emptyColumnsOrNullSqlAreNoOps() {
        GeometrySqlRewriter rewriter = new GeometrySqlRewriter(new MySQLGeometryStrategy());
        assertThat(rewriter.rewrite("SELECT * FROM shop", GeometryColumns.EMPTY, false)).isEqualTo("SELECT * FROM shop");
        assertThat(rewriter.rewrite("SELECT * FROM shop", (GeometryColumns) null, false)).isEqualTo("SELECT * FROM shop");
        assertThat(rewriter.rewrite(null, SHOP, false)).isNull();
    }

    // ------------------------------------------------------------------ PostgreSQL

    @Test
    void postgisEwkbWrapping() {
        GeometrySqlRewriter rewriter = new GeometrySqlRewriter(TestStrategies.postgisEwkb());
        assertThat(rewriter.rewrite("SELECT id,name,location FROM shop WHERE id=?", SHOP, true))
            .isEqualTo("SELECT id,name,encode(ST_AsEWKB(location), 'hex') AS location FROM shop WHERE id=?");
        assertThat(rewriter.rewrite("SELECT * FROM shop s LIMIT ? OFFSET ?", SHOP, true))
            .isEqualTo("SELECT s.id, s.name, encode(ST_AsEWKB(s.location), 'hex') AS location FROM shop s LIMIT ? OFFSET ?");
        assertThat(rewriter.rewrite("SELECT location::text, location FROM shop", SHOP, true))
            .isEqualTo("SELECT location::text, encode(ST_AsEWKB(location), 'hex') AS location FROM shop");
    }

    @Test
    void postgresQuotingRules() {
        GeometryColumns columns = new GeometryColumns("public.\"Shop\"", List.of("\"Geom\""), List.of("id", "\"Geom\""));
        GeometrySqlRewriter rewriter = new GeometrySqlRewriter(TestStrategies.postgisEwkb());
        assertThat(rewriter.rewrite("SELECT id,\"Geom\" FROM public.\"Shop\" WHERE id=?", columns, true))
            .isEqualTo("SELECT id,encode(ST_AsEWKB(\"Geom\"), 'hex') AS \"Geom\" FROM public.\"Shop\" WHERE id=?");
        assertThat(rewriter.rewrite("SELECT * FROM \"Shop\" AS \"S\"", columns, true))
            .isEqualTo("SELECT \"S\".id, encode(ST_AsEWKB(\"S\".\"Geom\"), 'hex') AS \"Geom\" FROM \"Shop\" AS \"S\"");
        // dollar quotes and escape strings hide commas, quotes and keywords
        assertThat(rewriter.rewrite(
            "SELECT $$\"Geom\", x$$ AS s, E'it\\'s, from' AS e, \"Geom\" FROM \"Shop\"", columns, true))
            .isEqualTo("SELECT $$\"Geom\", x$$ AS s, E'it\\'s, from' AS e, "
                + "encode(ST_AsEWKB(\"Geom\"), 'hex') AS \"Geom\" FROM \"Shop\"");
    }

    @Test
    void mysqlDoubleQuotesAreStringLiterals() {
        // without ANSI_QUOTES, "location" is a string constant in MySQL and must not be wrapped
        assertThat(mysql("SELECT \"location\" FROM shop")).isEqualTo("SELECT \"location\" FROM shop");
        assertThat(new GeometrySqlRewriter(TestStrategies.postgisEwkb()).rewrite("SELECT \"location\" FROM shop", SHOP, true))
            .isEqualTo("SELECT encode(ST_AsEWKB(\"location\"), 'hex') AS \"location\" FROM shop");
    }

    @Test
    void productionPostgisStrategyExpression() {
        GeometryHandlerStrategy strategy = new PostGISGeometryStrategy();
        String expression = GeometrySqlRewriter.wrapExpression(strategy, "s.location", SqlDialect.POSTGRESQL);
        assertThat(expression).contains("s.location").doesNotEndWith("AS location");
        assertThat(new GeometrySqlRewriter(strategy).rewrite("SELECT s.id, s.location FROM shop s", SHOP, true))
            .isEqualTo("SELECT s.id, " + expression + " AS location FROM shop s");
    }

    @Test
    void productionMySqlStrategyExpression() {
        assertThat(GeometrySqlRewriter.wrapExpression(new MySQLGeometryStrategy(), "t.`point`", SqlDialect.MYSQL))
            .isEqualTo("HEX(t.`point`)");
    }

    @Test
    void wrapExpressionStripsOnlyATrailingAlias() {
        assertThat(wrap(column -> "ST_AsBinary(" + column + ")")).isEqualTo("ST_AsBinary(x)");
        assertThat(wrap(column -> "CONCAT('a AS b', " + column + ") as \"y\"")).isEqualTo("CONCAT('a AS b', x)");
        assertThat(wrap(column -> "(" + column + " || ' AS x')")).isEqualTo("(x || ' AS x')");
        assertThat(wrap(column -> "  HEX(" + column + ")  AS  x  ")).isEqualTo("HEX(x)");
        assertThat(wrap(column -> "CAST(" + column + " AS text)")).isEqualTo("CAST(x AS text)");
        assertThat(wrap(column -> "HEX(" + column + ") AS 'x'")).isEqualTo("HEX(x)");
        assertThat(wrap(column -> "'unterminated")).isEqualTo("'unterminated");
        assertThatThrownBy(() -> wrap(column -> null)).isInstanceOf(IllegalStateException.class)
            .hasMessageContaining("wrapColumnForSelect");
        assertThatThrownBy(() -> wrap(column -> "  ")).isInstanceOf(IllegalStateException.class);
    }

    private static String wrap(java.util.function.UnaryOperator<String> wrapping) {
        return GeometrySqlRewriter.wrapExpression(
            new TestStrategies.Wrapping(DatabaseType.MYSQL, wrapping), "x", SqlDialect.MYSQL);
    }

    // ------------------------------------------------------------------ caching

    @Test
    void resultsAreCachedPerSqlText() {
        TestStrategies.Wrapping strategy = TestStrategies.mysqlHex();
        GeometrySqlRewriter rewriter = new GeometrySqlRewriter(strategy);
        String first = rewriter.rewrite("SELECT id,location FROM shop WHERE id=?", SHOP, true);
        String second = rewriter.rewrite(new String("SELECT id,location FROM shop WHERE id=?"), SHOP, true);
        assertThat(second).isSameAs(first).isEqualTo("SELECT id,HEX(location) AS location FROM shop WHERE id=?");
        assertThat(strategy.wrapCalls).hasValue(1);
        assertThat(rewriter.cacheSize()).isEqualTo(1);

        // different metadata or table matching mode are different entries
        rewriter.rewrite("SELECT id,location FROM shop WHERE id=?", SHOP, false);
        rewriter.rewrite("SELECT id,location FROM shop WHERE id=?",
            new GeometryColumns("shop", List.of("location"), null), true);
        assertThat(rewriter.cacheSize()).isEqualTo(3);

        rewriter.clearCache();
        assertThat(rewriter.cacheSize()).isZero();
    }

    @Test
    void cacheIsBounded() {
        GeometrySqlRewriter rewriter = new GeometrySqlRewriter(new MySQLGeometryStrategy());
        for (int i = 0; i < GeometrySqlRewriter.CACHE_LIMIT + 100; i++) {
            rewriter.rewrite("SELECT id, location FROM shop WHERE id = " + i, SHOP, true);
            assertThat(rewriter.cacheSize()).isLessThanOrEqualTo(GeometrySqlRewriter.CACHE_LIMIT);
        }
    }

    @Test
    void longStatementsAreRewrittenButNotCached() {
        GeometrySqlRewriter rewriter = new GeometrySqlRewriter(new MySQLGeometryStrategy());
        String in = "SELECT id, location FROM shop WHERE id IN (" + "?,".repeat(GeometrySqlRewriter.MAX_CACHED_SQL_LENGTH) + "?)";
        assertThat(rewriter.rewrite(in, SHOP, true)).startsWith("SELECT id, HEX(location) AS location FROM shop WHERE id IN (?,?");
        assertThat(rewriter.cacheSize()).isZero();
    }

    @Test
    void defaultStrategyIsResolvedOnEveryCall() {
        GeometrySqlRewriter rewriter = new GeometrySqlRewriter();
        GeometrySqlRewriter nullStrategy = new GeometrySqlRewriter(null);
        GeometryStrategyFactory.setDefaultStrategy(GeometryStrategyFactory.getStrategy(DatabaseType.MYSQL));
        assertThat(rewriter.rewrite("SELECT location FROM shop", SHOP, true)).startsWith("SELECT HEX(location)");
        assertThat(nullStrategy.rewrite("SELECT location FROM shop", SHOP, true)).startsWith("SELECT HEX(location)");

        TestStrategies.Wrapping postgis = TestStrategies.postgisEwkb();
        GeometryStrategyFactory.setDefaultStrategy(postgis);
        assertThat(rewriter.currentStrategy()).isSameAs(postgis);
        assertThat(rewriter.rewrite("SELECT location FROM shop", SHOP, true))
            .isEqualTo("SELECT encode(ST_AsEWKB(location), 'hex') AS location FROM shop");
        assertThat(nullStrategy.rewrite("SELECT location FROM shop", SHOP, true))
            .isEqualTo("SELECT encode(ST_AsEWKB(location), 'hex') AS location FROM shop");
    }

    @Test
    void strategyFailureIsThrownOnceThenTheOriginalIsCached() {
        TestStrategies.Wrapping failing = new TestStrategies.Wrapping(DatabaseType.MYSQL, column -> {
            throw new IllegalStateException("boom");
        });
        GeometrySqlRewriter rewriter = new GeometrySqlRewriter(failing);
        String sql = "SELECT location FROM shop";
        assertThatThrownBy(() -> rewriter.rewrite(sql, SHOP, true)).hasMessage("boom");
        assertThat(rewriter.rewrite(sql, SHOP, true)).isSameAs(sql);
        assertThat(failing.wrapCalls).hasValue(1);
    }

    @Test
    void strategyReportingNoDatabaseTypeUsesMySqlRules() {
        GeometryHandlerStrategy strategy = new TestStrategies.Wrapping(null, column -> "HEX(" + column + ")") {
            @Override
            public DatabaseType getSupportedDatabaseType() {
                throw new UnsupportedOperationException();
            }
        };
        assertThat(new GeometrySqlRewriter(strategy).rewrite("SELECT location FROM shop # c", SHOP, true))
            .isEqualTo("SELECT HEX(location) AS location FROM shop # c");
    }

    // ------------------------------------------------------------------ legacy API

    @Test
    void legacyApiMatchesByNameAndExpandsWithTheGivenColumns() {
        GeometrySqlRewriter rewriter = new GeometrySqlRewriter(new MySQLGeometryStrategy());
        assertThat(rewriter.rewrite("SELECT * FROM anything a", Set.of("location"), List.of("id", "location")))
            .isEqualTo("SELECT a.id, HEX(a.location) AS location FROM anything a");
        assertThat(rewriter.rewrite("SELECT * FROM anything", Set.of("location"), null))
            .isEqualTo("SELECT * FROM anything");
        assertThat(rewriter.rewrite("SELECT location FROM anything", Set.of("location"), List.of()))
            .isEqualTo("SELECT HEX(location) AS location FROM anything");
        assertThat(rewriter.rewrite("SELECT location FROM t", Set.of(), null)).isEqualTo("SELECT location FROM t");
        assertThat(rewriter.rewrite("SELECT location FROM t", null, null)).isEqualTo("SELECT location FROM t");
        assertThat(rewriter.rewrite(null, Set.of("location"), null)).isNull();
    }

    @Test
    void legacyApiNeverThrowsAndLogsOnce() {
        Logger logger = (Logger) LoggerFactory.getLogger(GeometrySqlRewriter.class);
        ListAppender<ILoggingEvent> appender = new ListAppender<>();
        appender.start();
        logger.addAppender(appender);
        try {
            GeometrySqlRewriter rewriter = new GeometrySqlRewriter(new TestStrategies.Wrapping(DatabaseType.MYSQL,
                column -> {
                    throw new IllegalArgumentException("Illegal group reference");
                }));
            assertThat(rewriter.rewrite("SELECT location FROM a", Set.of("location"), null))
                .isEqualTo("SELECT location FROM a");
            assertThat(rewriter.rewrite("SELECT location FROM b", Set.of("location"), null))
                .isEqualTo("SELECT location FROM b");
            assertThat(appender.list.stream().filter(e -> e.getLevel() == ch.qos.logback.classic.Level.WARN))
                .hasSize(1);
        } finally {
            logger.detachAppender(appender);
        }
    }
}
